### PR TITLE
Update build-integration-website-hosting.md

### PR DESCRIPTION
**Pull request by brad-za**
I ran into an issue where CRA apps or VITE react apps would not work or load correctly with the BrowserRouter from react-router-dom. It took me a considerable amount of time to figure out the cause of the issue and fix it. I hope this is helpful (:

### CODE REVIEW

**Review by BOBOKaa — COMMENTED** [review]
Thank you for your feedback, please pay attention to the format

**Comment by brad-za** [comment]
What do you mean by that? Is there a format guide I should follow? Where could I add my suggestion if possible? thanks

**Comment by BOBOKaa** [comment]
just add "-" at the beginning of the paragraph to align the context

**Comment by brad-za** [comment]
thanks for the feedback, I have updated it (:

**Review by BOBOKaa — APPROVED** [review]

**Pull request merged**
