### PR TITLE
Update build-integration-website-hosting.md

### PR DESCRIPTION
**Pull request by vinoparadiso**
In my first time going though this i did not have the crust CLI installed - I got tripped up for about 30 mins until I realised that so I thought I would add it to the documentation.

### CODE REVIEW

**Comment by BOBOKaa** [comment]
Thanks,please help to update [docs](https://github.com/crustio/crust-wiki/blob/mainnet/website/translated_docs/zh-CN/build-integration-website-hosting.md)

**Review by MITCHELLNEAL1 — COMMENTED** [review]
good

**Comment by MITCHELLNEAL1** [comment]
good

**Review by wuhaixian1984 — APPROVED** [review]
LGTM

**Pull request merged**
